name: convenient_test_manager_dart
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.1
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  args: ^2.6.0
  collection: ^1.19.0
  convenient_test_common_dart: ^1.5.1
  fixnum: ^1.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  grpc: ^4.0.1
  intl: ">=0.17.0 <0.20.0"
  meta: ^1.15.0
  mobx: ^2.3.3+2
  protobuf: ^3.1.0
  recase: ^4.1.0
  synchronized: ^3.3.0+3
  test_api: '>=0.5.1 <0.8.0'
  vm_service: '>=11.3.0 <15.0.0'

dependency_overrides:
  convenient_test_common_dart:
    path: ../convenient_test_common_dart

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lint: ">=1.8.2 <3.0.0"
  mobx_codegen: ^2.6.1
  test: ^1.25.8
