name: convenient_test_common_dart
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.1
repository: https://github.com/fzyzcjy/flutter_convenient_test
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  collection: ^1.19.0
  fixnum: ^1.1.1
  grpc: ^4.0.1
  meta: ^1.15.0
  mobx: ^2.3.3+2
  protobuf: ^3.1.0
  quiver: ^3.2.2
  tuple: ^2.0.2
dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.8
