name: convenient_test_dev
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.1
repository: https://github.com/fzyzcjy/flutter_convenient_test

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  collection: ^1.19.0
  convenient_test:
    git:
      url: https://github.com/IgorShahin/flutter_convenient_test.git
      path: packages/convenient_test
  convenient_test_common:
    git:
      url: https://github.com/IgorShahin/flutter_convenient_test.git
      path: packages/convenient_test_common
  convenient_test_common_dart:
    git:
      url: https://github.com/IgorShahin/flutter_convenient_test.git
      path: packages/convenient_test_common_dart
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  grpc: ^4.0.1
  image: ^4.3.0
  integration_test:
    sdk: flutter
  intl: ">=0.17.0 <0.20.0"
  json_annotation: ^4.9.0
  lint: ">=1.8.2 <3.0.0"
  matcher: ^0.12.16+1
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.4
  recase: ^4.1.0
  test_api: '>=0.5.1 <0.8.0'
  tuple: ^2.0.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
# dependency_overrides:
#   convenient_test:
#     path: ../convenient_test
#   convenient_test_common:
#     path: ../convenient_test_common
#   convenient_test_common_dart:
#     path: ../convenient_test_common_dart

dependency_overrides:
  convenient_test_common:
    path: ../convenient_test_common
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
