name: convenient_test_common
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more
version: 1.5.1
repository: https://github.com/fzyzcjy/flutter_convenient_test
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  collection: ^1.19.0
  convenient_test_common_dart: ^1.5.1
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  grpc: ^4.0.1
  mobx: ^2.3.3+2
  protobuf: ^3.1.0
  quiver: ^3.2.2
  tuple: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=1.8.2 <3.0.0"
# dependency_overrides:
#   convenient_test_common_dart:
#     path: ../convenient_test_common_dart

dependency_overrides:
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
